bin: update secret for versa

diff --git a/public_common/bin/secret b/public_common/bin/secret
--- a/public_common/bin/secret
+++ b/public_common/bin/secret
@@ -1,17 +1,23 @@
 #!/usr/bin/env bash
 
+secrets_dir=~/"mounts/versa/secrets/"
+secret_file="$secrets_dir/$1"
+
 if [[ "$#" -ne 1 ]]; then
     echo "please provide a key" >&2
     exit 1
 fi
-
-secret_file='/tmp/dot-secrets'
-
-if [[ ! -e "$secret_file" ]]; then
-    kbfs_mount="$(keybase config get mountdir | tr -d '"')"
-    source_file="${kbfs_mount}/private/sentriz/secrets"
-    cp "$source_file" "$secret_file"
-    chmod 400 "$secret_file"
+if ! which gpg >/dev/null 2>&1; then
+    echo "please install gpg" >&2
+    exit 1
+fi
+if [[ ! -d "$secrets_dir" ]]; then
+    echo "secrets dir not found" >&2
+    exit 1
+fi
+if [[ ! -f "$secret_file" ]]; then
+    echo "secret file not found" >&2
+    exit 1
 fi
 
-grep -Po "^$1\ \K([^ ]+)$" "$secret_file"
+gpg --quiet --decrypt "$secret_file"
