bin: add more logging in upload scripts

diff --git a/conf_extra/bin/upload-home b/conf_extra/bin/upload-home
--- a/conf_extra/bin/upload-home
+++ b/conf_extra/bin/upload-home
@@ -2,6 +2,11 @@
 
 # senan kelly, 2020
 
+if not type -q jq >/dev/null 2>&1
+    echo "please install jq" >&2
+    exit 1
+end
+
 if test (count $argv) -ne 1
     echo "usage: upload-home <path to image>" >&2
     exit 1
@@ -17,15 +22,28 @@ if ! test -e "$image_path"
     exit 1
 end
 
-set -l image_id (
-    curl -s "$url_upload" \
+set -l response (
+    curl \
+        --silent \
+        --fail \
         --header (printf "X-API-Key: %s" $api_key) \
         --form "i=@$image_path" \
-    | jq -r '.result.id'
+        "$url_upload"
 )
-
-if test -n "$image_id"
-    echo "$url_public/$image_id"
-    isatty stdout || notify-send.sh 'screenshot' 'uploaded to home' >/dev/null 2>&1
-    exit
+if test -z "$response"
+    echo "failed to upload" >&2
+    exit 1
 end
+
+set -l image_id (echo "$response" | jq -r '.result.id')
+if test -z "$image_id"
+    echo "server returned unexpected response $response" >&2
+    exit 1
+end
+
+echo "$url_public/$image_id"
+
+if ! isatty stdout
+    notify-send.sh 'screenshot' 'uploaded to home' >/dev/null 2>&1
+end
+
diff --git a/conf_extra/bin/upload-imgur b/conf_extra/bin/upload-imgur
--- a/conf_extra/bin/upload-imgur
+++ b/conf_extra/bin/upload-imgur
@@ -23,17 +23,24 @@ end
 
 set response (curl \
     --silent \
+    --fail \
     --header "Authorization: Client-ID $client_id" \
     --form "image=@$image_path" \
     "$upload_url"
 )
-
-if ! echo "$response" | jq -e '.success' >/dev/null
-    echo "error response from imgur:" >&2
-    echo "$response" | jq -M '.data.error' >&2
+if test -z "$response"
+    echo "failed to upload" >&2
     exit 1
 end
 
-echo "$response" | jq -r '.data.link'
+set -l link (echo "$response" | jq -r '.data.link')
+if test -z "$link"
+    echo "server returned unexpected response $response" >&2
+    exit 1
+end
 
-isatty stdout || notify-send.sh 'screenshot' 'uploaded to imgur' >/dev/null 2>&1
+echo "$link"
+
+if ! isatty stdout
+    notify-send.sh 'screenshot' 'uploaded to imgur' >/dev/null 2>&1
+end
